name: Release

on:
  push:
    tags:
      - v*

jobs:
  only-tag-build:
    runs-on: ubuntu-latest
    steps:
      - name: Start only tag build
        run: echo "only tag build"
      - name: Show tag info
        run: echo "${{ github.ref }} - ${{ github.sha }}"
  